from api.v1.schemas import (
    CouponBase,
    CouponResponse,
    CouponUpdate,
    CouponUsageResponse,
    GiftBase,
    GiftResponse,
    GiftUpdate,
    GiftUsageResponse,
    KeyDetailsResponse,
    KeyResponse,
    ReferralResponse,
    ServerBase,
    ServerResponse,
    ServerUpdate,
    TariffBase,
    TariffResponse,
    TariffUpdate,
    UserBase,
    UserResponse,
    UserUpdate,
    BlockedUserResponse,
    ManualBanResponse,
    NotificationResponse,
    PaymentResponse,
    TemporaryDataResponse,
    TrackingSourceResponse,
)
from api.v1.schemas.keys import KeyBase, KeyCreateRequest, KeyUpdate
from api.v1.schemas.settings import SettingResponse, SettingUpsert
from api.v2.schemas.web import WebBlockResponse, WebTheme, WebPageResponse, WebPageUpdate